# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('R', 'raw'), ('C', 'composite')], max_length=1)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='userparticipation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='metric',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.UserParticipation'),
        ),
    ]
