# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:38
from __future__ import unicode_literals

import sys
from django.db import migrations


def move_data(apps, schema_editor):
    activity = apps.get_model("activities", "Activity")
    entity = apps.get_model("activities", "Entity")
    objects_total = activity.objects.all().count()
    current_index = 1
    for activity_row in activity.objects.all():
        new_entity, created = entity.objects.get_or_create(name=activity_row.name)
        activity_row.entity_id = new_entity.id
        activity_row.save()
        if current_index % 100 == 0:
            percentage = (current_index / objects_total) * 100
            print("\rProgress: " + "{0:.2f}".format(percentage) + "%", end='')
        current_index += 1


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0002_auto_20171007_1623'),
    ]

    operations = [
        migrations.RunPython(move_data)
    ]
