# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('activities', '0004_remove_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.UserParticipation'),
        ),
        migrations.AddField(
            model_name='group',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.UserParticipation'),
        ),
    ]
